-- 1. Instantiate the data source schema

DO $$
DECLARE
	pgAppAgent varchar := 'symphony';  									-- the configured application database user agent
BEGIN

CREATE SCHEMA IF NOT EXISTS symphony;

EXECUTE format('ALTER DATABASE %I SET search_path TO symphony,public', current_database());
EXECUTE FORMAT ('GRANT USAGE ON SCHEMA symphony TO  %s', pgAppAgent);

SET search_path TO symphony,public; -- for session / maybe redundant;

CREATE TABLE IF NOT EXISTS areatype
(
    atype_id          integer GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT atype_pk
            PRIMARY KEY,
    atype_name        text
        CONSTRAINT atype_name
            UNIQUE,
    atype_coastalarea boolean DEFAULT FALSE NOT NULL
);

EXECUTE FORMAT ('ALTER TABLE areatype OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON areatype TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS baselineversion
(
    bver_id           integer GENERATED ALWAYS AS IDENTITY (START WITH 4)
        CONSTRAINT bver_pk
            PRIMARY KEY,
    bver_name         text                                        NOT NULL
        CONSTRAINT bver_name
            UNIQUE,
    bver_desc         text,
    bver_validfrom    date                                        NOT NULL,
    bver_ecofilepath  text                                        NOT NULL,
    bver_presfilepath text                                        NOT NULL,
    bver_locale       varchar(10) DEFAULT 'en'::character varying NOT NULL
);

EXECUTE FORMAT ('ALTER TABLE baselineversion OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON baselineversion TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS batchcalculation
(
    batchcalc_id      integer GENERATED ALWAYS AS IDENTITY (START WITH 203)
        PRIMARY KEY,
    owner             varchar(255)                          NOT NULL,
    execution_id      integer,
    entities          integer[]                             NOT NULL,
    calculated        integer[] DEFAULT ARRAY []::integer[] NOT NULL,
    failed            integer[] DEFAULT ARRAY []::integer[] NOT NULL,
    areas_calculation boolean   DEFAULT FALSE               NOT NULL,
    areas_options     json
);

EXECUTE FORMAT ('ALTER TABLE batchcalculation OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON batchcalculation TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS meta_bands
(
    metaband_id               integer GENERATED ALWAYS AS IDENTITY
        CONSTRAINT metaband_pk
            PRIMARY KEY,
    metaband_bver_id          integer              NOT NULL
        CONSTRAINT metaband_bver_fk
            REFERENCES baselineversion
            ON UPDATE CASCADE ON DELETE CASCADE,
    metaband_category         varchar(64)          NOT NULL,
    metaband_number           integer              NOT NULL,
    metaband_default_selected boolean DEFAULT TRUE NOT NULL,
    CONSTRAINT metaband_uq
        UNIQUE (metaband_bver_id, metaband_category, metaband_number)
);

EXECUTE FORMAT ('ALTER TABLE meta_bands OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON meta_bands TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS meta_values
(
    metaval_id       integer GENERATED ALWAYS AS IDENTITY
        CONSTRAINT metaval_pk
            PRIMARY KEY,
    metaval_band_id  integer      NOT NULL
        CONSTRAINT metaval_band_fk
            REFERENCES meta_bands,
    metaval_language varchar(2)   NOT NULL,
    metaval_field    varchar(255) NOT NULL,
    metaval_value    text         NOT NULL,
    CONSTRAINT metavalue_uq
        UNIQUE (metaval_band_id, metaval_language, metaval_field)
);

EXECUTE FORMAT ('ALTER TABLE meta_values OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON meta_values TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS nationalarea
(
    narea_id          integer GENERATED ALWAYS AS IDENTITY (START WITH 115)
        CONSTRAINT narea_pk
            PRIMARY KEY,
    narea_countryiso3 text NOT NULL,
    narea_areas       text,
    narea_type        text,
    narea_types       text
);

EXECUTE FORMAT ('ALTER TABLE nationalarea OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON nationalarea TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS scenariosnapshot
(
    id                             integer GENERATED ALWAYS AS IDENTITY (START WITH 1990)
        PRIMARY KEY,
    baselineid                     integer                    NOT NULL,
    changes                        json,
    ecosystems                     integer[]                  NOT NULL,
    polygon                        json                       NOT NULL,
    name                           varchar(255)               NOT NULL,
    normalization_type             integer                    NOT NULL,
    normalization_userdefinedvalue double precision           NOT NULL,
    owner                          varchar(255)               NOT NULL,
    pressures                      integer[]                  NOT NULL,
    timestamp                      timestamp                  NOT NULL,
    normalization_stddevmultiplier double precision DEFAULT 1 NOT NULL,
    areas                          json                       NOT NULL,
    normalization_value            double precision[],
    area_matrix_map                integer[]                  NOT NULL
);

EXECUTE FORMAT ('ALTER TABLE scenariosnapshot OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON scenariosnapshot TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS calculationresult
(
    cares_id                  integer GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    cares_baselinecalculation boolean                                                    NOT NULL,
    cares_calculationname     varchar(255)                                               NOT NULL,
    cares_impactmatrix        double precision[][]                                       NOT NULL,
    cares_owner               varchar(255)                                               NOT NULL,
    cares_geotiff             bytea,
    cares_timestamp           timestamp                                                  NOT NULL,
    cares_bver_id             integer                                                    NOT NULL
        CONSTRAINT cares__bver_fk
            REFERENCES baselineversion,
    scenariosnapshot_id       integer                                                    NOT NULL
        CONSTRAINT cares_ss_fk
            REFERENCES scenariosnapshot,
    cares_op                  varchar(255) DEFAULT 'CumulativeImpact'::character varying NOT NULL,
    cares_op_options          json,
    cares_image               bytea
);

EXECUTE FORMAT ('ALTER TABLE calculationresult OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON calculationresult TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS scenario
(
    id                             integer GENERATED ALWAYS AS IDENTITY (START WITH 1988)
        PRIMARY KEY,
    name                           varchar(255)               NOT NULL,
    baselineid                     integer                    NOT NULL,
    ecosystems                     integer[],
    pressures                      integer[],
    changes                        json,
    normalization_type             integer,
    normalization_userdefinedvalue double precision           NOT NULL,
    normalization_stddevmultiplier double precision DEFAULT 1 NOT NULL,
    owner                          varchar(255)               NOT NULL,
    timestamp                      timestamp                  NOT NULL,
    operation                      smallint         DEFAULT 0 NOT NULL,
    operation_options              json,
    latestcalculation_cares_id     integer
        CONSTRAINT latestcalculation_cares_fk
            REFERENCES calculationresult
            ON UPDATE CASCADE ON DELETE SET NULL
);

EXECUTE FORMAT ('ALTER TABLE scenario OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON scenario TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS sensitivitymatrix
(
    sensm_id      integer GENERATED ALWAYS AS IDENTITY (START WITH 246)
        CONSTRAINT sensm_pk
            PRIMARY KEY,
    sensm_name    text    NOT NULL,
    sensm_bver_id integer NOT NULL
        CONSTRAINT sensm_bver_fk
            REFERENCES baselineversion,
    sensm_owner   text
);

EXECUTE FORMAT ('ALTER TABLE sensitivitymatrix OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON sensitivitymatrix TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS calculationarea
(
    carea_id               integer GENERATED ALWAYS AS IDENTITY (START WITH 4039)
        CONSTRAINT carea_pk
            PRIMARY KEY,
    carea_name             text                  NOT NULL,
    carea_default          boolean DEFAULT FALSE NOT NULL,
    carea_default_sensm_id integer               NOT NULL
        CONSTRAINT carea_default_sensm_fk
            REFERENCES sensitivitymatrix,
    carea_maxvalue         double precision,
    carea_atype_id         integer
        CONSTRAINT carea_atype_fk
            REFERENCES areatype
);

EXECUTE FORMAT ('ALTER TABLE calculationarea OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON calculationarea TO  %s', pgAppAgent);

CREATE INDEX IF NOT EXISTS calc_sens_fk_inx
    ON calculationarea (carea_default_sensm_id);

CREATE INDEX IF NOT EXISTS carea_atype_fk_inx
    ON calculationarea (carea_atype_id);

CREATE TABLE IF NOT EXISTS calcareasensmatrix
(
    casen_id       integer GENERATED ALWAYS AS IDENTITY (START WITH 876)
        CONSTRAINT casen_pk
            PRIMARY KEY,
    casen_carea_id integer NOT NULL
        CONSTRAINT casen_carea_fk
            REFERENCES calculationarea,
    casen_sensm_id integer
        CONSTRAINT casen_sensm_fk
            REFERENCES sensitivitymatrix
            ON UPDATE CASCADE ON DELETE CASCADE,
    casen_comment  text
);

EXECUTE FORMAT ('ALTER TABLE calcareasensmatrix OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON calcareasensmatrix TO  %s', pgAppAgent);

CREATE INDEX IF NOT EXISTS casen_carea_fk_inx
    ON calcareasensmatrix (casen_carea_id);

CREATE INDEX IF NOT EXISTS casen_sensm_fk_inx
    ON calcareasensmatrix (casen_sensm_id);

CREATE TABLE IF NOT EXISTS capolygon
(
    cap_id       integer GENERATED ALWAYS AS IDENTITY (START WITH 590)
        CONSTRAINT cap_pk
            PRIMARY KEY,
    cap_carea_id integer NOT NULL
        CONSTRAINT cap_carea_fk
            REFERENCES calculationarea,
    cap_polygon  text    NOT NULL,
    pg_polygon   geometry(MultiPolygon, 4326)
);

EXECUTE FORMAT ('ALTER TABLE capolygon OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON capolygon TO  %s', pgAppAgent);

CREATE INDEX IF NOT EXISTS caplygon_gix1
    ON capolygon USING gist (st_geomfromgeojson(cap_polygon));

CREATE TABLE IF NOT EXISTS scenarioarea
(
    id               integer GENERATED ALWAYS AS IDENTITY (START WITH 496)
        PRIMARY KEY,
    changes          json,
    feature          json    NOT NULL,
    matrix           json,
    scenario         integer NOT NULL
        CONSTRAINT fk_scenarioarea_scenario_id
            REFERENCES scenario
            ON UPDATE CASCADE ON DELETE CASCADE,
    excluded_coastal integer,
    custom_calcarea  integer
        CONSTRAINT fk_scenarioarea_ca
            REFERENCES calculationarea
            ON UPDATE CASCADE ON DELETE SET NULL,
    polygon          geometry(MultiPolygon, 4326)
);

EXECUTE FORMAT ('ALTER TABLE scenarioarea OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON scenarioarea TO  %s', pgAppAgent);

CREATE INDEX IF NOT EXISTS fki_fk_scenarioarea_scenario_id
    ON scenarioarea (scenario);

CREATE TABLE IF NOT EXISTS sensitivity
(
    sens_id           integer GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    sens_pres_band_id integer NOT NULL
        CONSTRAINT sens_pres_band_fk
            REFERENCES meta_bands
            ON UPDATE CASCADE ON DELETE CASCADE,
    sens_eco_band_id  integer NOT NULL
        CONSTRAINT sens_eco_band_fk
            REFERENCES meta_bands
            ON UPDATE CASCADE ON DELETE CASCADE,
    sens_value        numeric NOT NULL,
    sens_sensm_id     integer NOT NULL
        CONSTRAINT sens_sensm_fk
            REFERENCES sensitivitymatrix
            ON UPDATE CASCADE ON DELETE CASCADE
);

EXECUTE FORMAT ('ALTER TABLE sensitivity OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON sensitivity TO  %s', pgAppAgent);

CREATE INDEX IF NOT EXISTS sensm_bver_fk_inx
    ON sensitivitymatrix (sensm_bver_id);

CREATE TABLE IF NOT EXISTS userdefarea_category
(
    uda_cat_id     integer GENERATED ALWAYS AS IDENTITY (START WITH 1)
        CONSTRAINT uda_cat_pk
            PRIMARY KEY,
    uda_cat_name   text NOT NULL
        CONSTRAINT uda_cat_name_uq
            UNIQUE,
    uda_cat_owner   text NOT NULL
)
EXECUTE FORMAT ('ALTER TABLE userdefarea_category OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON userdefarea_category TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS userdefarea
(
    uda_id          integer GENERATED ALWAYS AS IDENTITY (START WITH 2280)
        CONSTRAINT uda_pk
            PRIMARY KEY,
    uda_name        text NOT NULL,
    uda_description text,
    uda_polygon     text NOT NULL,
    uda_owner       text NOT NULL,
    uda_category_id integer
        CONSTRAINT uda_cat_fk
            REFERENCES userdefarea_category
                ON DELETE SET NULL
);

EXECUTE FORMAT ('ALTER TABLE userdefarea OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON userdefarea TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS compoundcomparison
(
    id               integer GENERATED ALWAYS AS IDENTITY
        CONSTRAINT comparisondata_pkey
            PRIMARY KEY,
    baseline_id      integer                                    NOT NULL
        CONSTRAINT fk_cmpdata_baseline
            REFERENCES baselineversion
            ON UPDATE CASCADE ON DELETE CASCADE,
    cmp_name         varchar(255) DEFAULT ''::character varying NOT NULL,
    cmp_calculations integer[]                                  NOT NULL,
    cmp_result       json                                       NOT NULL,
    cmp_owner        varchar(255)                               NOT NULL,
    cmp_timestamp    timestamp                                  NOT NULL
);

EXECUTE FORMAT ('ALTER TABLE compoundcomparison OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON compoundcomparison TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS usersettings
(
    "user"   varchar(255)            NOT NULL
        PRIMARY KEY,
    settings json DEFAULT '{}'::json NOT NULL
);

EXECUTE FORMAT ('ALTER TABLE usersettings OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON usersettings TO  %s', pgAppAgent);

CREATE TABLE IF NOT EXISTS reliabilitypartition
(
    rp_id          integer GENERATED ALWAYS AS IDENTITY
        CONSTRAINT uncertaintyextent_pkey
            PRIMARY KEY,
    rp_metaband_id integer NOT NULL
        CONSTRAINT fk_uce_band_id
            REFERENCES meta_bands,
    rp_value       integer NOT NULL,
    rp_polygon     geometry(MultiPolygon, 4326)
);

EXECUTE FORMAT ('ALTER TABLE reliabilitypartition OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON reliabilitypartition TO  %s', pgAppAgent);

CREATE OR REPLACE VIEW calculationresultslice
            (id, baselineversion_id, calculationname, timestamp, owner, ispurged, haschanges) AS
SELECT cr.cares_id                                   AS id,
       cr.cares_bver_id                              AS baselineversion_id,
       cr.cares_calculationname                      AS calculationname,
       cr.cares_timestamp                            AS "timestamp",
       cr.cares_owner                                AS owner,
       cr.cares_geotiff IS NULL                      AS ispurged,
       (((s.changes ->> 'baseChanges'::text)::json) ->> 'PRESSURE'::text) IS NOT NULL OR
       (((s.changes ->> 'baseChanges'::text)::json) ->> 'ECOSYSTEM'::text) IS NOT NULL OR
       ((SELECT COUNT(ac.key) AS count
         FROM JSON_EACH((s.changes ->> 'areaChanges'::text)::json) ac(key, value)
         WHERE NOT ac.value::text = '{}'::text)) > 0 AS haschanges
FROM symphony.scenariosnapshot s
         JOIN symphony.calculationresult cr ON cr.scenariosnapshot_id = s.id;

EXECUTE FORMAT ('ALTER VIEW calculationresultslice OWNER TO %s', pgAppAgent);
EXECUTE FORMAT ('GRANT SELECT ON calculationresultslice TO %s', pgAppAgent);

END
$$;
